### ISSUE TITLE
@ is very thin on thicker weights

### ISSUE THREAD

**Issue by morganholly** [intel/intel-one-mono#1]
I first noticed this on the preview image, where each of the characters looks a different weight except ! and $. After installing the font, # looks fine, but @ stays thin for thicker weights which looks out of place to me. It is a more complex character to do thick and small, but I've seen some very good takes on that from other fonts, often by losing the hole in the center a.
<img width="303" alt="image" src="https://github.com/intel/intel-one-mono/assets/98441016/e73bf163-0fcd-4659-b765-ad1c6a74a457">
<img width="155" alt="image" src="https://github.com/intel/intel-one-mono/assets/98441016/6b091e4b-bfdb-4d92-8024-415606a5ac2d">

**Comment by MatthewTurrini** [comment]
Thanks for noting this. We'll look into it.

**Comment by MatthewTurrini** [comment]
This intentional. It's a point of differentiation. It allows the @ (and a few others characters in teh set) to stand out within surrounding characters.
