### ISSUE TITLE
Unexpected behavior of the backtick ( ` ) character

### ISSUE THREAD

**Issue by houssameddine-h** [intel/intel-one-mono#11]
Here is a list of some characters followed by the backtick **`** character:

![backtick_demo](https://github.com/intel/intel-one-mono/assets/69154176/8f7e15e6-6ccb-4613-a9da-b34e06972140)

Programming languages use the backtick as a standalone character for different purposes and it shouldn't be combined with the preceding character.

For the grave accent placed over some letters in certain languages there are already standalone characters for them.
Example: à, è, ò, ...
These are already defined in the typeface.

**Comment by omenos** [comment]
This should be resolved in 1.2 (see #3), but the current solution causes issues for accented characters (#10).

**Comment by houssameddine-h** [comment]
I verified in the 1.2 version and indeed it was corrected.

![backtick_demo_2](https://github.com/intel/intel-one-mono/assets/69154176/ea6a3547-d079-4cae-896f-ae7da14ae23b)

Thanks!
