### ISSUE TITLE
Add ExtraBold variant

### ISSUE THREAD

**Issue by yavorski** [intel/intel-one-mono#16]
Please consider to add `ExtraBold` variant. 10x!

**Comment by Gso-1** [comment]
Entendido podría cumplir lo que usted me solicita pero yo cobro 45000 por la suscripción y de pronto cumplir su petición deagregarlo

**Comment by YVVT** [comment]
> Entendido podría cumplir lo que usted me solicita pero yo cobro 45000CLP por la suscripción y de pronto cumplir su petición de agregarlo

？

**Comment by TobiasFrereJones** [comment]
Duplicate of #38
