### ISSUE TITLE
__MACOSX directory in release files

### ISSUE THREAD

**Issue by krzyk** [intel/intel-one-mono#2]
Please remove __MACOSX directory that is in the release zip files, it doesn't look good.

**Comment by jacereda** [comment]
I just tried to package it for Guix and the package failed miserably because of this. I could workaround that in the package, but it would be better if this was fixed upstream.

**Comment by jpcirrus** [comment]
And the `.DS_Store` file in the font directories.

**Comment by mrfragger** [comment]
Just showing how to do it for any mac users.
`zip -r somedir.zip . -x '*.DS_Store’
`
Navigate to the directory you wish to zip on mac and this avoids putting `.DS_Store` and `__MACOSX` folders which are annonying for Linux and Windows users.
