### ISSUE TITLE
@ stroke is too thin

### ISSUE THREAD

**Issue by steelman** [intel/intel-one-mono#20]
The stroke width of `@` symbol is visibly thinner than in other characters. It shouldn't be.
![at](https://github.com/intel/intel-one-mono/assets/77683/4e2937e1-5060-4473-b9d8-86aab5d8d8d6)

**Comment by TobiasFrereJones** [comment]
This glyph was deliberately drawn lighter. The goal was to avoid blooming or blurring with too much weight, but also to emphasize its distinction from any adjacent alphanumeric characters.

**Comment by steelman** [comment]
IMHO this is not a valid point at this moment as `@` is the only character with a thinner stroke. By this logic other non-alphanumeric characters also "deserve" thinner stroke to distinguish them from numbers and letters.
