### ISSUE TITLE
Lowercase R seems misfit 

### ISSUE THREAD

**Issue by mh-firouzjah** [intel/intel-one-mono#23]
Although the letter `i` also has a small horizontal underline, the letter `r` has a completely different shape compared to other letters, and the horizontal lines drawn at the bottom and at the mouth of the letter aren't interesting.

**Comment by TobiasFrereJones** [comment]
Hello, and thanks for the comment. After feedback from users, this character was drawn to eliminate potential confusion with other letters. 

Additionally, some lowercase letters are conventionally narrow (f i j l r t). The monospaced premise requires these letters to have proportions that may feel wider than convention would suggest.
