### ISSUE TITLE
Please add glyphs (icons) support - Nerd Fonts Patch

### ISSUE THREAD

**Issue by Kunniii** [intel/intel-one-mono#37]
Currently, the font is missing some icons. I wanted to use this font in my terminal, but the lacks of icons make the terminal ugly!

I don't actually know how to patch a Font, like Nerd  Font, but something like that would be super cool!!

**Comment by rwmitchell** [comment]
Some terminals, such as iTerm2, support using a second font just for glyphs, which alleviates some of that issue.

MacVim doesn't.  I too support having the nerd font additions.  Maybe Nerd Font could pick up distributing Intel-One ?

**Comment by GLaDOS-418** [comment]
there's an open issue in nerdfonts issue for that

https://github.com/ryanoasis/nerd-fonts/issues/1238

**Comment by dtrodr** [comment]
Just came across this and saw it was merged recently:
https://github.com/ryanoasis/nerd-fonts/pull/1275

**Comment by Kunniii** [comment]
Thanks for notifying me! The font from nerd-fonts works great!!!
