### ISSUE TITLE
Spacing in Eclipse editor

### ISSUE THREAD

**Issue by ClodoaldoPinto** [intel/intel-one-mono#41]
When using Intel One Mono in Eclipse SQL editor the bold size or spacing is bigger then the regular one:

![Anotação 2023-07-14 153313](https://github.com/intel/intel-one-mono/assets/1433209/fa05a47b-50f3-435e-852a-351c2035d1f8)

When using Consolas it is the same: 

![Anotação 2023-07-14 153628](https://github.com/intel/intel-one-mono/assets/1433209/0b9f383d-e304-4cb9-b21e-25d7a7316ee8)

Is it the expected behavior?

**Comment by FredShallcrass** [comment]
Thanks for the screenshots.

This seems to be coming from a style linking setting in the fonts that will be addressed in the next release.
