### ISSUE TITLE
render result is not right in pycharm subpixel mode

### ISSUE THREAD

**Issue by sevelee** [intel/intel-one-mono#42]
I am using .otf version of release v1.2.1 
windows 10 22h2, 1080p monitor

You could see that render result is weird and hard to read.
![image](https://github.com/intel/intel-one-mono/assets/8036235/bb395160-7e88-4368-a182-d402a1543fb2)

pycharm setting:
![image](https://github.com/intel/intel-one-mono/assets/8036235/bf2c89a6-f794-4a26-a75d-37d4d94024bc)

**Comment by FredShallcrass** [comment]
If you are using Windows, try installing the .ttf versions of the fonts. This will contain the manual hinting which is optimised for Windows.
