### ISSUE TITLE
Small alignment issue for dash (U+002D)

### ISSUE THREAD

**Issue by galdor** [intel/intel-one-mono#5]
As visible in this screenshot, the dash character is not vertically aligned with plus and equal characters. Programming fonts often try to maintain these characters vertically aligned because they are used for ASCII art, e.g. to represent boxes.

![intelone](https://github.com/intel/intel-one-mono/assets/37804/abb69d75-6667-4093-9554-cd3fa4ba1335)

**Comment by stepanbujnak** [comment]
Also if used as `->` to access a field on a pointer the "arrow" looks malformed.

**Comment by jsejcksn** [comment]
In absence of early feedback from a maintainer, here's more (perhaps counter-) perspective. From [`README.md`](https://github.com/intel/intel-one-mono/blob/a78bea53fb9069813061ece45a8c814cdd3c3636/README.md?plain=1#L9):

> Identifying the typographically underserved low-vision developer audience, The Intel Brand Team designed the Intel One Mono typeface together with VMLY&R and Frere-Jones Type, for maximum legibility to address developers' fatigue and eyestrain and reduce coding errors. A panel of low-vision and legally blind developers provided feedback at each stage of design.

According to that paragraph in the document, it would be natural for this typeface to strive to make it easier for viewers to discriminate glyphs, and perfect alignment is not necessarily a positive quality in regard to low-vision discrimination.

**Comment by galdor** [comment]
After more tests, the vertical alignment of `:` and `=` is particularly bad, this is a completely deal breaker when using a language with a `:=` operator such as Go.

**Comment by MatthewTurrini** [comment]
Thanks for the feedback. We're looking into this with the font designer.

**Comment by MatthewTurrini** [comment]
We are looking in to all combinations of operators effected by teh combination of colon and dash.

**Comment by nahaki** [comment]
Thanks for sharing

**Comment by DawnDawnKeppel** [comment]
Thank you, this is great news!
