### ISSUE TITLE
Incorrect font family name in Readme.md

### ISSUE THREAD

**Issue by hanrai** [intel/intel-one-mono#56]
OS: Windows 11 Pro
Font Version: 1.200 ttf

I found a bug in the Readme.md file of the project. The bug is that the font name is specified as "Intel One Mono" when explaining how to set the VSCode font family, but the actual correct spelling should be "IntelOne Mono".

I really like this font and appreciate the work done by the project team. I hope this issue can be resolved soon. Thank you.

**Comment by principis** [comment]
This has been fixed in [V1.3.0](https://github.com/intel/intel-one-mono/tree/V1.3.0).
