### ISSUE TITLE
Please add Thin, ExtraLight variations.

### ISSUE THREAD

**Issue by jasonm23** [intel/intel-one-mono#7]
Due to optic/vision issues (Light sensitivity), I experience an exponentially better viewing/writing experience when I use a typeface that is extremely thin (IBM Plex Mono Thin for example) however the choices available are very limited.

Please consider adding Thin and/or ExtraLight variations.

**Comment by MatthewTurrini** [comment]
Thanks for the feedback. We'll review your request and consider.

**Comment by DawnDawnKeppel** [comment]
nice

**Comment by TobiasFrereJones** [comment]
Duplicate of #38
